version: '8.0'
services:
  db:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'administrator'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'vicinanza-studios'
    ports:
     - '3306:3306'
    volumes:
     - /D:/Source/iamty/Documents/Dev/Alchemetrics/alchemetrics_nextJS/nextjs-flask/var/lib/mysql