version: '8.0'
services:
  db:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'vicinanza-studios'
      MYSQL_USER: 'administrator'
      MYSQL_PASSWORD: 'admin'
    ports:
     - '3306:3306'
    volumes:
     - ./var/lib/mysql