version: '8.0'
services:
  db:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'Password!'
      MYSQL_DATABASE: 'vicinanza-studios'
      MYSQL_USER: 'tarroyo'
      MYSQL_PASSWORD: 'Password!'
    ports:
     - '3306:3306'
    volumes:
     - ./var/lib/mysql