version: 'latest'

services:

  db:
    image: 'mysql/mysql-server:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'Password!'
      MYSQL_DATABASE: 'distribution_db'
      MYSQL_USER: 'tarroyo'
      MYSQL_PASSWORD: 'Password!'
    ports:
     - '3306:3306'